version: '3.8'

services:
    flask:
        restart: always
        image: qwlake/flask-crawling-server:latest
        container_name: crawling-server
        ports:
            - "8080:8080"
        volumes:
            - /data/log/crawling-server/:/app/log/
            - /data/log/crawling-server/:/var/log/nginx/crawling-server/
